In [3]:
import pandas as pd
import numpy as np

In [4]:
marks = np.array([85, 25, 35, 72, 68, 95, 70])

print("Original Array")
print(marks)

print("Slice (index 1 to 4):", marks[1:5])

Original Array
[85 25 35 72 68 95 70]
Slice (index 1 to 4): [25 35 72 68]


In [5]:
print("First mark:", marks[0])


First mark: 85


In [6]:
print("Last mark:", marks[-1])  


Last mark: 70


In [7]:
print("First three marks:", marks[0:3]) 

First three marks: [85 25 35]


In [8]:
print("2 to 4 elements:", marks[2:5]) 

2 to 4 elements: [35 72 68]


In [9]:
print("Every second mark:", marks[::2]) 

Every second mark: [85 35 68 70]


In [10]:
print("Reverse:", marks[::-1]) 

Reverse: [70 95 68 72 35 25 85]


In [11]:
data = np.array([
    [85, 78, 90],
    [72, 80, 75],
    [90, 87, 95]
])
print(data)

[[85 78 90]
 [72 80 75]
 [90 87 95]]


In [12]:
d = {
    "Name": ["pushpa", "pragathi", "aishu", "vaishu"],
    "Marks": [92, 74, 85, 63],
    "Branch": ["ISE", "CSE", "AI", "ECE"]
}
data = pd.DataFrame(d)
print(data)

       Name  Marks Branch
0    pushpa     92    ISE
1  pragathi     74    CSE
2     aishu     85     AI
3    vaishu     63    ECE


In [13]:
print("First 2 Rows\n", data.iloc[:2])

First 2 Rows
        Name  Marks Branch
0    pushpa     92    ISE
1  pragathi     74    CSE


In [14]:
print(data.iloc[-1])  

Name      vaishu
Marks         63
Branch       ECE
Name: 3, dtype: object


In [15]:
print(data.iloc[1:3]) 

       Name  Marks Branch
1  pragathi     74    CSE
2     aishu     85     AI


In [16]:
print("Marks Column:\n", data["Marks"])

Marks Column:
 0    92
1    74
2    85
3    63
Name: Marks, dtype: int64


In [17]:
print("Rows where Marks > 70:\n", data[data["Marks"] > 70])

Rows where Marks > 70:
        Name  Marks Branch
0    pushpa     92    ISE
1  pragathi     74    CSE
2     aishu     85     AI
